package main

import (
	"os"
	"path/filepath"
	"sort"
	"strings"
	"text/template"
)

var (
	basePath   = "./internal/generators/data/generated/data/minecraft"
	outFile    = "./internal/mc/registries_data_generated.go"
	registries = []string{
		"worldgen/biome",
		"chat_type",
		"trim_pattern",
		"trim_material",
		"wolf_variant",
		"wolf_sound_variant",
		"pig_variant",
		"frog_variant",
		"cat_variant",
		"cow_variant",
		"chicken_variant",
		"painting_variant",
		"dimension_type",
		"damage_type",
		"banner_pattern",
		// "enchantment", this seems to create a protocol error
		"jukebox_song",
		"instrument",
		"test_environment",
		"test_instance",
	}
)

const tpl = `// Code generated by generators/registries_data. DO NOT EDIT.
package mc

import "go/types"

var RegistriesData = []RegistryData{
{{- range . }}
    {
        ID: String("minecraft:{{.ID}}"),
        Entries: PrefixedArray[RegistryDataEntry]{
            Slice: &[]RegistryDataEntry{
{{- range .Entries }}
                {
                    ID:   String("minecraft:{{.}}"),
                    Data: PrefixedOptional[types.Nil]{Has: false},
                },
{{- end }}
            },
        },
    },
{{- end }}
}
`

func main() {
	var data []map[string]any

	for _, name := range registries {
		absPath := filepath.Join(basePath, name)
		files, err := os.ReadDir(absPath)
		if err != nil {
			panic(err)
		}

		var entries []string

		for _, f := range files {
			if f.IsDir() || !strings.HasSuffix(f.Name(), ".json") {
				continue
			}
			// todo: load the actual nbt data
			entry := strings.TrimSuffix(f.Name(), ".json")
			entries = append(entries, entry)
		}
		sort.Strings(entries)
		data = append(data, map[string]any{
			"ID":      name,
			"Entries": entries,
		})
	}

	t := template.Must(template.New("reg").Parse(tpl))
	f, err := os.Create(outFile)
	if err != nil {
		panic(err)
	}

	defer f.Close()
	_ = t.Execute(f, data)
}
