package main

import (
	"encoding/json"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"text/template"
)

var (
	basePath      = "internal/mcdata/data/minecraft"
	tagsPath      = "internal/mcdata/data/minecraft/tags"
	registriesRpt = "internal/mcdata/reports/registries.json"
	outFile       = "internal/mc/registries_data_gen.go"
	// staticRegistries are built into the client rather than sent as registry
	// data, so only their tags go over the wire. Entry IDs come from the
	// registries report instead of datapack ordering. dimension_type's
	// infiniburn field references a block tag, so block is not optional.
	staticRegistries = []string{
		"block",
		"item",
		"fluid",
		"entity_type",
		"game_event",
		"point_of_interest_type",
		"potion",
	}
	registries = []string{
		"worldgen/biome",
		"chat_type",
		"trim_pattern",
		"trim_material",
		"wolf_variant",
		"wolf_sound_variant",
		"pig_variant",
		"pig_sound_variant",
		"frog_variant",
		"cat_variant",
		"cat_sound_variant",
		"cow_variant",
		"cow_sound_variant",
		"chicken_variant",
		"chicken_sound_variant",
		"zombie_nautilus_variant",
		"painting_variant",
		"dimension_type",
		// world_clock and timeline are referenced by dimension_type as of 26.2
		// (default_clock / timelines); the client cannot parse its own built-in
		// dimension_type entries unless both are synced.
		"world_clock",
		"timeline",
		"damage_type",
		"banner_pattern",
		// "enchantment", this seems to create a protocol error
		"jukebox_song",
		"instrument",
		"test_environment",
		"test_instance",
	}
)

// tmplData splits the two payloads: only dynamic registries are sent as
// registry data, but tags are sent for dynamic and static registries alike.
type tmplData struct {
	Registries []registry
	Tags       []taggedRegistry
}

type registry struct {
	ID string
	// Entries are sorted; an entry's index is the numeric ID the client assigns
	// it, which is what tags reference on the wire.
	Entries []string
}

type taggedRegistry struct {
	ID   string
	Tags []tag
}

type tag struct {
	Name    string
	Entries []int
}

// tagFile is the datapack representation of a tag. Values are either a plain
// entry ID, a "#namespace:tag" reference to another tag, or an object form
// carrying a required flag.
type tagFile struct {
	Values []tagValue `json:"values"`
}

type tagValue struct {
	ID string
}

func (v *tagValue) UnmarshalJSON(b []byte) error {
	if err := json.Unmarshal(b, &v.ID); err == nil {
		return nil
	}
	var obj struct {
		ID string `json:"id"`
	}
	if err := json.Unmarshal(b, &obj); err != nil {
		return err
	}
	v.ID = obj.ID
	return nil
}

const tpl = `// Code generated by gen-registries-data; DO NOT EDIT.
package mc

import (
	"github.com/Gagonlaire/mcgoserv/internal/proto"
)

var RegistriesData = []RegistryData{
{{- range .Registries }}
	{
		ID: proto.String("minecraft:{{.ID}}"),
		Entries: proto.PrefixedArray[RegistryDataEntry, *RegistryDataEntry]{
			Data: []RegistryDataEntry{
{{- range .Entries }}
				{
					ID:   proto.String("minecraft:{{.}}"),
					Data: proto.PrefixedOptional[proto.Byte, *proto.Byte]{},
				},
{{- end }}
			},
		},
	},
{{- end }}
}

var RegistriesTags = proto.NewPrefixedArray[RegistryTags, *RegistryTags]([]RegistryTags{
{{- range .Tags }}
	{
		ID: proto.String("minecraft:{{.ID}}"),
		Tags: proto.PrefixedArray[TagEntry, *TagEntry]{
			Data: []TagEntry{
{{- range .Tags }}
				{
					Name:    proto.String("minecraft:{{.Name}}"),
					Entries: proto.PrefixedArray[proto.VarInt, *proto.VarInt]{Data: []proto.VarInt{ {{- range $i, $e := .Entries}}{{if $i}}, {{end}}{{$e}}{{end -}} }},
				},
{{- end }}
			},
		},
	},
{{- end }}
})
`

func main() {
	var data tmplData

	for _, name := range registries {
		reg := registry{ID: name}

		files, err := os.ReadDir(filepath.Join(basePath, name))
		if err != nil {
			panic(err)
		}
		for _, f := range files {
			if f.IsDir() || !strings.HasSuffix(f.Name(), ".json") {
				continue
			}
			// todo: load the actual nbt data
			reg.Entries = append(reg.Entries, strings.TrimSuffix(f.Name(), ".json"))
		}
		sort.Strings(reg.Entries)

		ids := make(map[string]int, len(reg.Entries))
		for i, e := range reg.Entries {
			ids[e] = i
		}

		data.Registries = append(data.Registries, reg)
		data.Tags = append(data.Tags, taggedRegistry{ID: name, Tags: collectTags(name, ids)})
	}

	for _, name := range staticRegistries {
		data.Tags = append(data.Tags, taggedRegistry{ID: name, Tags: collectTags(name, protocolIDs(name))})
	}

	t := template.Must(template.New("reg").Parse(tpl))
	f, err := os.Create(outFile)
	if err != nil {
		panic(err)
	}

	defer f.Close()
	_ = t.Execute(f, data)
}

// protocolIDs reads the network IDs a static registry's entries are assigned by
// the client, keyed by unprefixed entry name.
func protocolIDs(regName string) map[string]int {
	content, err := os.ReadFile(registriesRpt)
	if err != nil {
		panic(err)
	}

	var report map[string]struct {
		Entries map[string]struct {
			ProtocolID int `json:"protocol_id"`
		} `json:"entries"`
	}
	if err := json.Unmarshal(content, &report); err != nil {
		panic(err)
	}

	reg, ok := report["minecraft:"+regName]
	if !ok {
		panic("registry " + regName + " not found in " + registriesRpt)
	}

	ids := make(map[string]int, len(reg.Entries))
	for name, entry := range reg.Entries {
		ids[strings.TrimPrefix(name, "minecraft:")] = entry.ProtocolID
	}
	return ids
}

// collectTags reads every tag defined for a registry and flattens it to the
// numeric entry IDs the wire format carries. Tag-to-tag references are inlined
// and entries absent from the registry are dropped, mirroring the client's
// handling of optional tag values.
func collectTags(regName string, ids map[string]int) []tag {
	root := filepath.Join(tagsPath, regName)
	if _, err := os.Stat(root); err != nil {
		return nil
	}

	raw := make(map[string]tagFile)
	err := filepath.WalkDir(root, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() || !strings.HasSuffix(path, ".json") {
			return nil
		}
		rel, err := filepath.Rel(root, path)
		if err != nil {
			return err
		}
		content, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		var tf tagFile
		if err := json.Unmarshal(content, &tf); err != nil {
			return err
		}
		raw[strings.TrimSuffix(filepath.ToSlash(rel), ".json")] = tf
		return nil
	})
	if err != nil {
		panic(err)
	}

	names := make([]string, 0, len(raw))
	for name := range raw {
		names = append(names, name)
	}
	sort.Strings(names)

	tags := make([]tag, 0, len(names))
	for _, name := range names {
		tags = append(tags, tag{Name: name, Entries: flatten(name, raw, ids, map[string]bool{})})
	}
	return tags
}

func flatten(name string, raw map[string]tagFile, ids map[string]int, seen map[string]bool) []int {
	if seen[name] {
		return nil
	}
	seen[name] = true

	var out []int
	for _, v := range raw[name].Values {
		id := strings.TrimPrefix(v.ID, "minecraft:")
		if ref, ok := strings.CutPrefix(id, "#"); ok {
			out = append(out, flatten(strings.TrimPrefix(ref, "minecraft:"), raw, ids, seen)...)
			continue
		}
		if idx, ok := ids[id]; ok {
			out = append(out, idx)
		}
	}
	return dedupe(out)
}

func dedupe(in []int) []int {
	seen := make(map[int]bool, len(in))
	out := in[:0]
	for _, v := range in {
		if seen[v] {
			continue
		}
		seen[v] = true
		out = append(out, v)
	}
	return out
}
