package main

import (
	"encoding/json"
	"fmt"
	"os"
)

const versionTpl = `// Code generated by gen-version; DO NOT EDIT.
package mcdata

const (
	ProtocolVersion = %d
	GameVersion     = "%s"
)
`

func main() {
	data, _ := os.ReadFile("version.json")
	var config struct {
		Protocol int    `json:"protocol_version"`
		Game     string `json:"game_version"`
	}
	json.Unmarshal(data, &config)

	f, _ := os.Create("internal/mcdata/version_gen.go")
	defer f.Close()

	fmt.Fprintf(f, versionTpl, config.Protocol, config.Game)
}
