package main

import (
	"embed"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"reflect"
	"text/template"
	"unicode"
)

//go:embed tmpl/*.tmpl
var tmplFS embed.FS

type Field struct {
	Name string
}

type StructData struct {
	StructName string
	Fields     []Field
}

const header = `// Code generated by gen-field; DO NOT EDIT.
package mc

import (
	"io"
)

`

func main() {
	fset := token.NewFileSet()
	pkgs, _ := parser.ParseDir(fset, ".", nil, parser.ParseComments)
	f, err := os.Create("field_gen.go")
	if err != nil {
		panic(err)
	}

	rftmpl := template.Must(template.ParseFS(tmplFS, "tmpl/readfrom.tmpl"))
	wttmpl := template.Must(template.ParseFS(tmplFS, "tmpl/writeto.tmpl"))

	defer f.Close()
	_, _ = f.WriteString(header)

	for _, pkg := range pkgs {
		for _, fAst := range pkg.Files {
			for _, decl := range fAst.Decls {
				g, ok := decl.(*ast.GenDecl)
				if !ok {
					continue
				}

				for _, spec := range g.Specs {
					ts, ok := spec.(*ast.TypeSpec)
					if !ok {
						continue
					}
					st, ok := ts.Type.(*ast.StructType)
					if !ok {
						continue
					}

					if g.Doc != nil && hasGenerateImpl(g.Doc.List) {
						var fields []Field
						for _, field := range st.Fields.List {
							if hasFieldIgnoreTag(field) {
								continue
							}
							for _, name := range field.Names {
								// only keep exported fields
								if name.Name != "" && unicode.IsUpper([]rune(name.Name)[0]) {
									fields = append(fields, Field{Name: name.Name})
								}
							}
						}
						data := StructData{
							StructName: ts.Name.Name,
							Fields:     fields,
						}
						_ = rftmpl.Execute(f, data)
						_ = wttmpl.Execute(f, data)
					}
				}
			}
		}
	}
}

func hasGenerateImpl(comments []*ast.Comment) bool {
	for _, c := range comments {
		if c.Text == "//go:generate-field-impl" {
			return true
		}
	}
	return false
}

func hasFieldIgnoreTag(field *ast.Field) bool {
	if field.Tag == nil {
		return false
	}
	// field.Tag.Value includes the backticks, e.g. `field:"-"`
	tag := reflect.StructTag(field.Tag.Value[1 : len(field.Tag.Value)-1])
	return tag.Get("field") == "-"
}
