// gen-field generates ReadFrom(io.Reader) and/or WriteTo(io.Writer) methods
//
// Usage: go run ./cmd/gen-field <directory>
//
// Directive (placed above a struct):
//
//	//field:encode [mode=read|write|both]
//
// Directive parameters:
//   - mode — "both" (default), "read", or "write". Controls which methods are generated.
//
// Struct field tag (to exclude a field):
//
//	`field:"-"`
//
// Generated:
//   - ReadFrom(r io.Reader) (int64, error)  — reads each field sequentially from the reader.
//   - WriteTo(w io.Writer) (int64, error)   — writes each field sequentially to the writer.
package main

import (
	"embed"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"text/template"
)

//go:embed tmpl/*.tmpl
var tmplFS embed.FS

type Field struct {
	Name string
}

type StructData struct {
	StructName string
	Fields     []Field
	Mode       string // "read", "write", "both"
}

func main() {
	if len(os.Args) < 2 {
		fmt.Fprintf(os.Stderr, "usage: gen-field <directory>\n")
		os.Exit(1)
	}
	dir := os.Args[1]

	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, dir, func(fi os.FileInfo) bool {
		return !strings.HasSuffix(fi.Name(), "_gen.go")
	}, parser.ParseComments)
	if err != nil {
		fmt.Fprintf(os.Stderr, "parse error: %v\n", err)
		os.Exit(1)
	}

	var pkgName string
	var structs []StructData

	for _, pkg := range pkgs {
		pkgName = pkg.Name
		for _, file := range pkg.Files {
			processFile(file, &structs)
		}
	}

	if len(structs) == 0 {
		return
	}

	outPath := filepath.Join(dir, "field_gen.go")
	out, err := os.Create(outPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "create output: %v\n", err)
		os.Exit(1)
	}
	defer out.Close()

	fmt.Fprintf(out, "// Code generated by gen-field; DO NOT EDIT.\npackage %s\n\n", pkgName)
	fmt.Fprintf(out, "import (\n\t\"io\"\n)\n\n")

	tmpl := template.Must(template.ParseFS(tmplFS, "tmpl/*.tmpl"))

	for _, s := range structs {
		if s.Mode == "read" || s.Mode == "both" {
			if err := tmpl.ExecuteTemplate(out, "readfrom", s); err != nil {
				fmt.Fprintf(os.Stderr, "template error (ReadFrom %s): %v\n", s.StructName, err)
				os.Exit(1)
			}
		}
		if s.Mode == "write" || s.Mode == "both" {
			if err := tmpl.ExecuteTemplate(out, "writeto", s); err != nil {
				fmt.Fprintf(os.Stderr, "template error (WriteTo %s): %v\n", s.StructName, err)
				os.Exit(1)
			}
		}
	}
}

func processFile(file *ast.File, structs *[]StructData) {
	for _, decl := range file.Decls {
		g, ok := decl.(*ast.GenDecl)
		if !ok || g.Tok != token.TYPE {
			continue
		}
		for _, spec := range g.Specs {
			ts, ok := spec.(*ast.TypeSpec)
			if !ok {
				continue
			}
			st, ok := ts.Type.(*ast.StructType)
			if !ok {
				continue
			}

			// find the //field:encode directive
			var directive string
			if g.Doc != nil {
				for _, c := range g.Doc.List {
					if strings.HasPrefix(c.Text, "//field:encode") {
						directive = c.Text
						break
					}
				}
			}
			if directive == "" && ts.Doc != nil {
				for _, c := range ts.Doc.List {
					if strings.HasPrefix(c.Text, "//field:encode") {
						directive = c.Text
						break
					}
				}
			}
			if directive == "" {
				continue
			}

			info := parseDirective(directive, ts.Name.Name)

			for _, field := range st.Fields.List {
				if hasFieldIgnoreTag(field) {
					continue
				}
				for _, name := range field.Names {
					if name.Name != "" {
						info.Fields = append(info.Fields, Field{Name: name.Name})
					}
				}
			}

			*structs = append(*structs, info)
		}
	}
}

func parseDirective(directive, structName string) StructData {
	info := StructData{
		StructName: structName,
		Mode:       "both",
	}

	parts := strings.Fields(strings.TrimPrefix(directive, "//field:encode"))
	for _, p := range parts {
		k, v, ok := strings.Cut(p, "=")
		if !ok {
			continue
		}
		switch k {
		case "mode":
			info.Mode = v
		}
	}

	return info
}

func hasFieldIgnoreTag(field *ast.Field) bool {
	if field.Tag == nil {
		return false
	}
	tag := reflect.StructTag(field.Tag.Value[1 : len(field.Tag.Value)-1])
	return tag.Get("field") == "-"
}
