package main

import (
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
	"strings"
	"unicode"
)

const (
	basePrismaJSURl    = "https://raw.githubusercontent.com/PrismarineJS/minecraft-data/master/data/"
	projectVersionFile = "version.json"
)

type DataPaths struct {
	Pc      map[string]map[string]string `json:"pc"`
	Bedrock map[string]map[string]string `json:"bedrock"`
}

type VersionData struct {
	ProtocolVersion int    `json:"protocol_version"`
	Version         string `json:"game_version"`
}

// order is important, some generators depend on data generated by others
var generators = map[string]func(reader io.ReadCloser, data map[string]any) error{
	"language":  generateLanguage,
	"sounds":    generateSounds,
	"blocks":    generateBlocks,
	"items":     generateItems,
	"materials": generateMaterials,
}

func main() {
	resp, err := http.Get(basePrismaJSURl + "dataPaths.json")
	if err != nil || resp.StatusCode != http.StatusOK {
		panic("Cannot fetch " + basePrismaJSURl)
	}

	var dataPaths DataPaths
	if err := json.NewDecoder(resp.Body).Decode(&dataPaths); err != nil {
		panic("Cannot decode " + basePrismaJSURl)
	}
	_ = resp.Body.Close()

	fileContent, err := os.ReadFile(projectVersionFile)
	if err != nil {
		panic(err)
	}

	var versionData VersionData
	if err := json.Unmarshal(fileContent, &versionData); err != nil {
		panic(err)
	}

	data := make(map[string]any)
	if versionInfo, ok := dataPaths.Pc[versionData.Version]; ok {
		for key, generator := range generators {
			url := fmt.Sprintf("%s%s/%s.json", basePrismaJSURl, versionInfo[key], key)
			resp, err := http.Get(url)

			if err != nil || resp.StatusCode != http.StatusOK {
				panic("Cannot fetch " + url)
			}

			if err := generator(resp.Body, data); err != nil {
				panic(err)
			}
			_ = resp.Body.Close()
		}
	} else {
		panic("Version " + versionData.Version + " not found in dataPaths.json")
	}
}

func toPascalCase(input string) string {
	if idx := strings.Index(input, ":"); idx != -1 {
		input = input[idx+1:]
	}

	parts := strings.FieldsFunc(input, func(r rune) bool {
		return r == '_' || r == ' ' || r == '-' || r == '.'
	})

	for i, part := range parts {
		if len(part) > 0 {
			r := []rune(part)
			r[0] = unicode.ToUpper(r[0])
			parts[i] = string(r)
		}
	}

	name := strings.Join(parts, "")
	if name == "Map" {
		return "MapBlock"
	}
	if name == "Func" {
		return "FuncBlock"
	}

	return name
}
