package main

import (
	"encoding/json"
	"fmt"
	"io"
	"log"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"unicode"
)

const (
	basePrismaJSURl    = "https://raw.githubusercontent.com/PrismarineJS/minecraft-data/master/data/"
	projectVersionFile = "version.json"
	cacheDir           = ".cache"
)

type DataPaths struct {
	Pc      map[string]map[string]string `json:"pc"`
	Bedrock map[string]map[string]string `json:"bedrock"`
}

type VersionData struct {
	ProtocolVersion int    `json:"protocol_version"`
	Version         string `json:"game_version"`
}

// order is important, some generators depend on data generated by others
var generators = map[string]func(reader io.ReadCloser, data map[string]any) error{
	"entities":  generateEntities,
	"language":  generateLanguage,
	"sounds":    generateSounds,
	"blocks":    generateBlocks,
	"items":     generateItems,
	"materials": generateMaterials,
}

func main() {
	if err := os.MkdirAll(cacheDir, 0755); err != nil {
		panic(err)
	}

	dataPathReader, err := getReader(basePrismaJSURl+"dataPaths.json", "dataPaths.json", true)
	if err != nil {
		panic("Cannot fetch dataPaths.json: " + err.Error())
	}

	var dataPaths DataPaths
	if err := json.NewDecoder(dataPathReader).Decode(&dataPaths); err != nil {
		panic("Cannot decode dataPaths.json")
	}
	_ = dataPathReader.Close()

	fileContent, err := os.ReadFile(projectVersionFile)
	if err != nil {
		panic(err)
	}

	var versionData VersionData
	if err := json.Unmarshal(fileContent, &versionData); err != nil {
		panic(err)
	}

	data := make(map[string]any)
	if versionInfo, ok := dataPaths.Pc[versionData.Version]; ok {
		for key, generator := range generators {
			url := fmt.Sprintf("%s%s/%s.json", basePrismaJSURl, versionInfo[key], key)
			fileName := fmt.Sprintf("%s_%s.json", versionData.Version, key)
			reader, err := getReader(url, fileName, false)

			if err != nil {
				panic("Cannot fetch " + url + ": " + err.Error())
			}

			if err := generator(reader, data); err != nil {
				panic(err)
			}
			_ = reader.Close()
		}
	} else {
		panic("Version " + versionData.Version + " not found in dataPaths.json")
	}
}

func getReader(url string, cacheFileName string, skipCache bool) (io.ReadCloser, error) {
	cachePath := filepath.Join(cacheDir, cacheFileName)

	if !skipCache {
		if _, err := os.Stat(cachePath); err == nil {
			log.Println("Using cached file:", cacheFileName)
			return os.Open(cachePath)
		}
	}

	log.Println("Downloading:", url)
	resp, err := http.Get(url)
	if err != nil || resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("failed to fetch url %s", url)
	}

	file, err := os.Create(cachePath)
	if err != nil {
		_ = resp.Body.Close()
		return nil, err
	}

	_, err = io.Copy(file, resp.Body)
	_ = resp.Body.Close()
	_ = file.Close()
	if err != nil {
		return nil, err
	}

	return os.Open(cachePath)
}

func toPascalCase(input string) string {
	if idx := strings.Index(input, ":"); idx != -1 {
		input = input[idx+1:]
	}

	parts := strings.FieldsFunc(input, func(r rune) bool {
		return r == '_' || r == ' ' || r == '-' || r == '.'
	})

	for i, part := range parts {
		if len(part) > 0 {
			r := []rune(part)
			r[0] = unicode.ToUpper(r[0])
			parts[i] = string(r)
		}
	}

	return strings.Join(parts, "")
}
