package main

import (
	"encoding/json"
	"fmt"
	"os"
	"sort"
	"strings"
	"text/template"
	"unicode"
)

const (
	inFile  = "internal/mcdata/reports/registries.json"
	outFile = "internal/mc/blockentity/type_gen.go"
	regKey  = "minecraft:block_entity_type"
)

type entry struct {
	ProtocolID int    `json:"protocol_id"`
	Name       string `json:"-"`
}

type registries struct {
	BlockEntityType struct {
		Entries map[string]entry `json:"entries"`
	} `json:"minecraft:block_entity_type"`
}

// TODO: move template in file and follow the prismarinejs generator, merge with gen-registry-data
const tpl = `// Code generated by gen-block-entity-types; DO NOT EDIT.
package blockentity

import "github.com/Gagonlaire/mcgoserv/internal/world"

type Type = world.BEType

type Properties struct {
	Name string
}

const (
{{- range . }}
	Type{{.Pascal}} Type = {{.ID}}
{{- end }}
)

var registry = [...]Properties{
{{- range . }}
	{Name: "{{.Name}}"},
{{- end }}
}

var idByName = map[string]Type{
{{- range . }}
	"{{.Name}}": Type{{.Pascal}},
{{- end }}
}
`

type row struct {
	ID     int
	Name   string
	Pascal string
}

func main() {
	raw, err := os.ReadFile(inFile)
	if err != nil {
		panic(err)
	}

	var r registries
	if err := json.Unmarshal(raw, &r); err != nil {
		panic(err)
	}
	if len(r.BlockEntityType.Entries) == 0 {
		panic("no block_entity_type entries found in " + inFile)
	}

	var rows []row
	for name, e := range r.BlockEntityType.Entries {
		rows = append(rows, row{
			ID:     e.ProtocolID,
			Name:   name,
			Pascal: toPascalCase(name),
		})
	}
	sort.Slice(rows, func(i, j int) bool { return rows[i].ID < rows[j].ID })

	for i, r := range rows {
		if r.ID != i {
			panic(fmt.Sprintf("non-dense protocol_id sequence: index %d has id %d (%s)", i, r.ID, r.Name))
		}
	}

	t := template.Must(template.New("be").Parse(tpl))
	f, err := os.Create(outFile)
	if err != nil {
		panic(err)
	}
	defer func() { _ = f.Close() }()
	if err := t.Execute(f, rows); err != nil {
		panic(err)
	}
}

func toPascalCase(input string) string {
	if idx := strings.Index(input, ":"); idx != -1 {
		input = input[idx+1:]
	}
	parts := strings.FieldsFunc(input, func(r rune) bool {
		return r == '_' || r == ' ' || r == '-' || r == '.'
	})
	for i, part := range parts {
		if len(part) > 0 {
			r := []rune(part)
			r[0] = unicode.ToUpper(r[0])
			parts[i] = string(r)
		}
	}
	return strings.Join(parts, "")
}
