package main

import (
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"text/template"
	"unicode"
)

type Field struct {
	Name string
}

type StructData struct {
	StructName string
	Fields     []Field
}

const baseTpl = `// Code generated by gen-fields; DO NOT EDIT.
package mc

import (
	"io"
)

`

const readFromTpl = `func (s *{{.StructName}}) ReadFrom(r io.Reader) (n int64, err error) {
{{- $first := true }}
{{- range .Fields }}
    {{- if $first }}
    nn, err := s.{{ .Name }}.ReadFrom(r)
    {{- $first = false }}
    {{- else }}
    nn, err = s.{{ .Name }}.ReadFrom(r)
    {{- end }}
    if err != nil {
        return n, err
    }
    n += nn
{{- end }}
    return n, nil
}

`

const writeToTpl = `func (s *{{.StructName}}) WriteTo(w io.Writer) (n int64, err error) {
{{- $first := true }}
{{- range .Fields }}
    {{- if $first }}
    nn, err := s.{{ .Name }}.WriteTo(w)
    {{- $first = false }}
    {{- else }}
    nn, err = s.{{ .Name }}.WriteTo(w)
    {{- end }}
    if err != nil {
        return n, err
    }
    n += nn
{{- end }}
    return n, nil
}

`

func main() {
	fset := token.NewFileSet()
	pkgs, _ := parser.ParseDir(fset, "internal/mc", nil, parser.ParseComments)
	f, err := os.Create("internal/mc/fields_gen.go")
	if err != nil {
		panic(err)
	}
	wttmpl := template.Must(template.New("writeto").Parse(writeToTpl))
	rftmpl := template.Must(template.New("readfrom").Parse(readFromTpl))

	defer f.Close()
	_, _ = f.WriteString(baseTpl)

	for _, pkg := range pkgs {
		for _, fAst := range pkg.Files {
			for _, decl := range fAst.Decls {
				g, ok := decl.(*ast.GenDecl)
				if !ok {
					continue
				}

				for _, spec := range g.Specs {
					ts, ok := spec.(*ast.TypeSpec)
					if !ok {
						continue
					}
					st, ok := ts.Type.(*ast.StructType)
					if !ok {
						continue
					}

					if g.Doc != nil && hasGenerateImpl(g.Doc.List) {
						var fields []Field
						for _, field := range st.Fields.List {
							for _, name := range field.Names {
								// only keep exported fields
								if name.Name != "" && unicode.IsUpper([]rune(name.Name)[0]) {
									fields = append(fields, Field{Name: name.Name})
								}
							}
						}
						data := StructData{
							StructName: ts.Name.Name,
							Fields:     fields,
						}
						_ = rftmpl.Execute(f, data)
						_ = wttmpl.Execute(f, data)
					}
				}
			}
		}
	}
}

func hasGenerateImpl(comments []*ast.Comment) bool {
	for _, c := range comments {
		if c.Text == "//go:generate-field-impl" {
			return true
		}
	}
	return false
}
