package main

import (
	"embed"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"text/template"
	"unicode"
)

//go:embed tmpl/*.tmpl
var tmplFS embed.FS

// encodeInfo data table to match a meta type to a protocol type
type encodeInfo struct {
	Cast string
	Raw  bool
}

var typeTable = map[string]encodeInfo{
	"Byte":              {Cast: "Byte"},
	"VarInt":            {Cast: "VarInt"},
	"VarLong":           {Cast: "VarLong"},
	"Float":             {Cast: "Float"},
	"String":            {Cast: "String"},
	"TextComponent":     {Cast: "TextComponent"},
	"Boolean":           {Cast: "Boolean"},
	"Rotations":         {Cast: "Rotations"},
	"Position":          {Cast: "Position"},
	"Direction":         {Cast: "Direction"},
	"BlockState":        {Cast: "VarInt"},
	"Pose":              {Cast: "VarInt"},
	"HumanoidArm":       {Cast: "Byte"},
	"CatVariant":        {Cast: "VarInt"},
	"WolfVariant":       {Cast: "VarInt"},
	"FrogVariant":       {Cast: "VarInt"},
	"PigVariant":        {Cast: "VarInt"},
	"ChickenVariant":    {Cast: "VarInt"},
	"PaintingVariant":   {Cast: "VarInt"},
	"SnifferState":      {Cast: "VarInt"},
	"ArmadilloState":    {Cast: "VarInt"},
	"OptPosition":       {Raw: true},
	"OptVarInt":         {Raw: true},
	"OptBlockState":     {Raw: true},
	"OptTextComponent":  {Raw: true},
	"OptUUID":           {Raw: true},
	"OptGlobalPosition": {Raw: true},
	"Slot":              {Raw: true},
	"Particle":          {Raw: true},
	"Particles":         {Raw: true},
	"VillagerData":      {Raw: true},
	"ResolvableProfile": {Raw: true},
	"Vector3":           {Raw: true},
	"Quaternion":        {Raw: true},
}

type MetaField struct {
	FieldName string
	FieldType string
	Index     string
	MetaType  string
	Cast      string
	Raw       bool
	IsFlags   bool
	NoSetter  bool
	NoEncode  bool
}

type StructInfo struct {
	Name     string
	Receiver string
	Mode     string // "entity" or "layer"
	Parents  []string
	Fields   []MetaField
}

func main() {
	if len(os.Args) < 2 {
		fmt.Fprintf(os.Stderr, "usage: gen-meta <directory>\n")
		os.Exit(1)
	}
	dir := os.Args[1]

	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, dir, func(fi os.FileInfo) bool {
		return !strings.HasSuffix(fi.Name(), "_gen.go")
	}, parser.ParseComments)
	if err != nil {
		fmt.Fprintf(os.Stderr, "parse error: %v\n", err)
		os.Exit(1)
	}

	var pkgName string
	var structs []StructInfo

	for _, pkg := range pkgs {
		pkgName = pkg.Name
		for _, file := range pkg.Files {
			processFile(file, &structs)
		}
	}

	if len(structs) == 0 {
		return
	}

	// Collect imports needed
	needsMC := false
	needsMetadata := false
	needsPacket := false
	for _, s := range structs {
		if len(s.Fields) > 0 {
			needsPacket = true
			for _, f := range s.Fields {
				if !f.NoEncode {
					needsMC = true
					needsMetadata = true
				}
				if !f.NoSetter && !f.Raw {
					// setter doesn't need mc/metadata, just MarkDirty
				}
			}
		}
	}

	outPath := filepath.Join(dir, "meta_gen.go")
	out, err := os.Create(outPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "create output: %v\n", err)
		os.Exit(1)
	}
	defer out.Close()

	fmt.Fprintf(out, "// Code generated by gen-meta; DO NOT EDIT.\npackage %s\n\n", pkgName)

	if needsMC || needsMetadata || needsPacket {
		fmt.Fprintf(out, "import (\n")
		if needsMC {
			fmt.Fprintf(out, "\t\"github.com/Gagonlaire/mcgoserv/internal/mc\"\n")
		}
		if needsMetadata {
			fmt.Fprintf(out, "\t\"github.com/Gagonlaire/mcgoserv/internal/mc/entities/metadata\"\n")
		}
		if needsPacket {
			fmt.Fprintf(out, "\t\"github.com/Gagonlaire/mcgoserv/internal/packet\"\n")
		}
		fmt.Fprintf(out, ")\n\n")
	}

	tmpl := template.Must(template.New("").Funcs(template.FuncMap{
		"singular":   singular,
		"lowerFirst": lowerFirst,
	}).ParseFS(tmplFS, "tmpl/*.tmpl"))

	for _, s := range structs {
		// Generate setters
		for _, f := range s.Fields {
			if f.NoSetter {
				continue
			}
			tplName := "setter"
			if f.IsFlags {
				tplName = "flagSetter"
			}
			data := map[string]any{
				"Recv":   s.Receiver,
				"Struct": s.Name,
				"Field":  f,
				"Mode":   s.Mode,
			}
			if err := tmpl.ExecuteTemplate(out, tplName, data); err != nil {
				fmt.Fprintf(os.Stderr, "template error (%s.%s): %v\n", s.Name, f.FieldName, err)
				os.Exit(1)
			}
		}

		// Generate EncodeMetadata
		data := map[string]any{
			"Recv":    s.Receiver,
			"Struct":  s.Name,
			"Parents": s.Parents,
			"Fields":  s.Fields,
			"Mode":    s.Mode,
		}
		if err := tmpl.ExecuteTemplate(out, "encodeMeta", data); err != nil {
			fmt.Fprintf(os.Stderr, "template error (EncodeMetadata %s): %v\n", s.Name, err)
			os.Exit(1)
		}
	}
}

func processFile(file *ast.File, structs *[]StructInfo) {
	directives := map[token.Pos]string{}
	if file.Comments != nil {
		for _, cg := range file.Comments {
			for _, c := range cg.List {
				if strings.HasPrefix(c.Text, "//meta:encode") {
					directives[c.End()] = c.Text
				}
			}
		}
	}

	for _, decl := range file.Decls {
		g, ok := decl.(*ast.GenDecl)
		if !ok || g.Tok != token.TYPE {
			continue
		}
		for _, spec := range g.Specs {
			ts, ok := spec.(*ast.TypeSpec)
			if !ok {
				continue
			}
			st, ok := ts.Type.(*ast.StructType)
			if !ok {
				continue
			}

			// find the //meta:encode directive for this struct
			var directive string
			if g.Doc != nil {
				for _, c := range g.Doc.List {
					if strings.HasPrefix(c.Text, "//meta:encode") {
						directive = c.Text
						break
					}
				}
			}
			if directive == "" && ts.Doc != nil {
				for _, c := range ts.Doc.List {
					if strings.HasPrefix(c.Text, "//meta:encode") {
						directive = c.Text
						break
					}
				}
			}
			if directive == "" {
				for pos, d := range directives {
					if pos <= ts.Pos() && ts.Pos()-pos < 100 {
						directive = d
						break
					}
				}
			}

			if directive == "" {
				continue
			}

			info := parseDirective(directive, ts.Name.Name)

			// parse fields
			for _, field := range st.Fields.List {
				if field.Tag == nil {
					continue
				}
				tag := reflect.StructTag(field.Tag.Value[1 : len(field.Tag.Value)-1])
				metaTag := tag.Get("meta")
				if metaTag == "" || metaTag == "-" {
					continue
				}

				for _, name := range field.Names {
					if !unicode.IsUpper([]rune(name.Name)[0]) {
						continue
					}
					mf := parseMetaTag(metaTag, name.Name, exprToString(field.Type))
					info.Fields = append(info.Fields, mf)
				}
			}

			*structs = append(*structs, info)
		}
	}
}

func parseDirective(directive, structName string) StructInfo {
	info := StructInfo{
		Name:     structName,
		Receiver: string(unicode.ToLower([]rune(structName)[0])),
		Mode:     "entity",
	}

	// parse parameters from "//meta:encode key=val key=val"
	parts := strings.Fields(strings.TrimPrefix(directive, "//meta:encode"))
	for _, p := range parts {
		k, v, ok := strings.Cut(p, "=")
		if !ok {
			continue
		}
		switch k {
		case "mode":
			info.Mode = v
		case "parents":
			info.Parents = strings.Split(v, ",")
		case "receiver":
			info.Receiver = v
		}
	}

	return info
}

func parseMetaTag(tag, fieldName, fieldType string) MetaField {
	parts := strings.Split(tag, ",")

	mf := MetaField{
		FieldName: fieldName,
		FieldType: fieldType,
	}

	if len(parts) >= 1 {
		mf.Index = strings.TrimSpace(parts[0])
	}
	if len(parts) >= 2 {
		mf.MetaType = strings.TrimSpace(parts[1])
	}

	for i := 2; i < len(parts); i++ {
		switch strings.TrimSpace(parts[i]) {
		case "flags":
			mf.IsFlags = true
		case "nosetter":
			mf.NoSetter = true
		case "noencode":
			mf.NoEncode = true
		}
	}

	if ei, ok := typeTable[mf.MetaType]; ok {
		mf.Cast = ei.Cast
		mf.Raw = ei.Raw
	} else {
		fmt.Fprintf(os.Stderr, "warning: unknown meta type %q for field %s, defaulting to raw\n", mf.MetaType, fieldName)
		mf.Raw = true
	}

	return mf
}

func exprToString(expr ast.Expr) string {
	switch e := expr.(type) {
	case *ast.Ident:
		return e.Name
	case *ast.SelectorExpr:
		return exprToString(e.X) + "." + e.Sel.Name
	case *ast.StarExpr:
		return "*" + exprToString(e.X)
	case *ast.ArrayType:
		if e.Len == nil {
			return "[]" + exprToString(e.Elt)
		}
		return "[" + exprToString(e.Len) + "]" + exprToString(e.Elt)
	case *ast.IndexListExpr:
		parts := make([]string, len(e.Indices))
		for i, idx := range e.Indices {
			parts[i] = exprToString(idx)
		}
		return exprToString(e.X) + "[" + strings.Join(parts, ", ") + "]"
	case *ast.IndexExpr:
		return exprToString(e.X) + "[" + exprToString(e.Index) + "]"
	case *ast.BasicLit:
		return e.Value
	default:
		return "UNKNOWN"
	}
}

func singular(s string) string {
	if strings.HasSuffix(s, "s") {
		return s[:len(s)-1]
	}
	return s
}

func lowerFirst(s string) string {
	if s == "" {
		return s
	}
	r := []rune(s)
	r[0] = unicode.ToLower(r[0])
	return string(r)
}
